iterative/dvc-objects

- .github/workflows/release.yml
- .github/workflows/tests.yml
- CONTRIBUTING.rst
- noxfile.py
- setup.cfg
- src/dvc_objects/fs/system.py
Part of https://github.com/iterative/dvc/issues/7708
Otherwise we are forced to create a conda package for `jaraco.windows`, which
is not a big deal, but since we are about to drop 3.7, might as well just do
that.
> dvc-objects: drop python 3.7

- src/dvc_objects/fs/implementations/gs.py
fixes resolution of relative paths (https://github.com/iterative/dvc/issues/7638)
fixes #38
> gs: add {_strip/unstrip}_protocol

- pyproject.toml
- src/dvc_objects/fs/implementations/oss.py
- tests/fs/test_strip_unstrip.py
Runcache tests were failing due to a lack of proper `_strip_protcol`/`unstrip_protcol` in OSS. Please check other inlined comments.
> oss: add _strip_protocol/unstrip_protocol; add tests

- src/dvc_objects/fs/implementations/gdrive.py
`pydrive2.auth.CommandLineAuth` uses out of band authentication (`urn:ietf:wg:oauth:2.0:oob`) which has been [deprecated](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html), breaking authentication for gdrive with oauth. 
Switching to LocalWebserverAuth solves the issue (thanks @shcheklein)
fixed iterative/dvc#7867
> gdrive: use LocalWebserverAuth instead of CommandLineAuth

- .github/workflows/tests.yml
Whenever the `setup-python` action would provide a new patch version of the python (as it happened with 3.10.4 -> 3.10.5), it'd break the caching of the virtual environment in the nox and would throw following (cryptic) error:
```
Error: python is not installed into the virtualenv, it is located at /opt/hostedtoolcache/Python/3.10.5/x64/bin/python. Pass external=True into run() to explicitly allow this.
```
It seems it's because the virtualenv has a broken symlink to the old interpreter that does not exist after the update.
https://github.com/actions/setup-python/issues/182 may be related.
With this change, the cache key now depends on the full python version instead of just major.minor. So this issue should hopefully not happen again, and automatically get invalidated.
Also see …
> gha: fix issue when caching virtual environments

- src/dvc_objects/obj.py
We are creating lots of these, so it will help to save up on memory and
improve performance.
Similar to https://github.com/iterative/dvc-data/pull/56
> obj: add __slots__

- src/dvc_objects/db.py
- src/dvc_objects/fs/base.py
- tests/conftest.py
- tests/test_odb.py
`write` is a low-level, *dumb* API to write the content with the `oid` as a key.
Makes it easier to setup odb for testing instead of doing `fs.pipe_file` + `odb.add()`. I think it is convenient to have this function instead of using two APIs.
> odb: introduce `add_bytes` API

- src/dvc_objects/transfer.py
- tests/test_transfer.py
This implements a very naive transfer mechanism without
batching (which should be a straightforward change after
we have batching in odb.add itself).
> transfer: add naive objects transfer function

- setup.cfg
- src/dvc_objects/fs/implementations/_memory.py
- src/dvc_objects/fs/implementations/memory.py
Usage:
```python
from dvc_objects.fs.implementations._memory import MemFS2
from dvc_objects.fs import MemoryFileSystem
memfs = MemFS2()
memfs = MemoryFileSystem(trie_based=True)
```
> fs: add trie-based, object-based in-mem fs

- .pre-commit-config.yaml
- src/dvc_objects/fs/implementations/_memory.py
- tests/fs/test_memfs.py
- Make it non-cacheable.
- Implement `rm`.
- Optimize `ls` (reduce 1 `info` call).
- Code cleanup.
- Lots of tests
> memfs2: make it non-cacheable, add tests, minor refactoring and optimizations

- src/dvc_objects/db.py
- tests/test_odb.py
Requires for testtool in dvc-data for supporting short_oid as an argument. I forgot to add in dvc-objects, thought I did.
It's not very optimal, but since we only require for one call in testtool, that should be fine.
https://github.com/iterative/dvc-data/commit/3e0362ac226ab0d0ff64ee1b778bb85fa681671c
> odb: add exists_prefix method

- src/dvc_objects/fs/base.py
`dir/` s3/etc objects are really just files with invalid names and instead of
giving them special treatment in the filesystem itself, we can simply ignore
them while collecting.
> ObjectFileSystem: remove special treatment for empty objects

- src/dvc_objects/fs/implementations/gdrive.py
Temporary fix for https://github.com/iterative/dvc/issues/7984
Proper fix is to stop asking for tmp_dir completely and simplify auth
https://github.com/iterative/PyDrive2/issues/193
> fs: gdrive: create temporary tmp_dir if not provided

- src/dvc_objects/fs/implementations/gdrive.py
No longer needed with in-memory cred handling.
Related to https://github.com/iterative/dvc/issues/7984
> fs: gdrive: remove redundant temp paths

- src/dvc_objects/db.py
- tests/test_odb.py
Also changed the implementation of `exists` to call `is_file()` instead of `exists()`.
The previous implementation was using `odb.all()` which goes through all the files in the cache which coupled to `path_to_oid` was very slow.
> odb: optimize exists_prefix and disallow short_oid of size <=2

- src/dvc_objects/fs/implementations/http.py
This seemingly minor change fixes pushing data to an HTTP remote storage with `dvc` v2.16.0. At the moment, `dvc` v2.16.0 cannot push _any data at all_ to an HTTP remote storage!
I noticed that with `dvc` v2.15.0 pushing data to an HTTP remote storage works fine while it doesn't work - i.e. data just isn't transferred without an error - with v2.16.0. Between `dvc` v2.15.0 and v2.16.0, `dvc-objects` (a transitive dependency of `dvc` via `dvc-data`) was bumped from v0.1.5 to v0.1.6 by the bump of `dvc-data` from v0.1.5 to v0.1.6. After some digging, I arrived at `dvc-objects` and #114 which, among other changes, changed the implementation of the [`ObjectDB.exists(...)`](https://github.com/iterative/dvc-objects/blob/ebee28733103ac2b13c5207f640394ff03603699/src/dvc_objects/db.py#L45-L46) …
> fs: http: fix `isfile` method

- src/dvc_objects/fs/implementations/http.py
We have been getting reports that the timeout on sock_read was raising
timeout error even for chunked uploads, and sometimes even uploading
zero-byte files.
See: https://github.com/iterative/dvc/issues/8065
and https://github.com/iterative/dvc/issues/8100.
These kinds of logic don't belong here and should be upstreamed (eg: RetryClient/ClientTimeout, etc).
We added timeout in https://github.com/iterative/dvc/pull/7460 because of freezes in
https://github.com/iterative/dvc/issues/7414.
I think we can rollback this for now given that there are lots of report of failures/issues with this line,
and if we get any new reports of hangs, we'll investigate it separately.
> fs: http: do not timeout on sock_read

- src/dvc_objects/fs/generic.py
Linux can return ENOTTY (25) on `ioctl` calls for devices that don't implement the requested ioctl type, so we need to include it in the set of expected errnos when trying to reflink.
https://man7.org/linux/man-pages/man2/ioctl.2.html
Will fix iterative/dvc#6980
> fs: generic: handle linux ENOTTY in _try_links

- setup.cfg
We no longer test these and they are really `dvc` (and not `dvc-objects`) plugins that will be registered through `dvc`.
> deps: don't install/depend on dvc plugins

- .github/workflows/tests.yml
When using previous concurrency method, whenever a release was made, running workflows for the sha in the main branch would cancel. This is not what we want, we want to only have one running workflow in a pull request but we don't want any limits on `release`/`main` branch.
Still, until further testing, I am hesitant to upstream this into py-template. Let's test this for a week.
> ci: simpler concurrency

- src/dvc_objects/fs/generic.py
Not all filesystems can silently delete it. Ran into this with adlfs.
> fs: test_links: ignore FileNotFoundError

- src/dvc_objects/fs/base.py
This avoids creating an fs instance.
> fs: version_aware: use fs_args instead of fs

- src/dvc_objects/db.py
- tests/test_odb.py
The structure is pre-defined so doing this step explicitly saves us a call on every object add (of which there are typically 100s of thousands or even millions).
> db: introduce init() to pre-create odb structure

- src/dvc_objects/db.py
- tests/test_odb.py
Reverts iterative/dvc-objects#145
See https://github.com/iterative/dvc-objects/pull/145#discussion_r973010258
> Revert "db: introduce init() to pre-create odb structure"

- src/dvc_objects/db.py
- tests/test_odb.py
Mostly convenience, to avoid manually messing with odb.fs.
> odb: add detele/clear methods

- src/dvc_objects/fs/_local.py
- src/dvc_objects/fs/local.py
While waiting for https://github.com/fsspec/filesystem_spec/pull/1053 to be released.
> localfs: temporarily patch fsspec's localfs

- src/dvc_objects/fs/callbacks.py
- src/dvc_objects/fs/generic.py
- `fs.generic.transfer` now wraps/branches callback
- So the original callback will now operate at the file level, and child callbacks will operate at the byte level when needed (i.e. when we use `copy()` instead of linking).
- callbacks now support wrapping `put_file`
> fs: use child callbacks in generic transfer

- src/dvc_objects/db.py
The latter is not available everywhere.
> db: use fs.path.name instead of fs.path.basename

- src/dvc_objects/db.py
Fixes #134
- ODBs no longer compared based on filesystem equality, instead they are compared based on protocol and path
> odb: make __eq__ and __hash__ behavior consistent

- src/dvc_objects/db.py
`odb.add()` now returns an int count of the number of files which were actually transferred. This gives us consistent behavior with progress + returned counts for functions that use the file transfer callback
> odb: return xfer count on odb.add

- src/dvc_objects/fs/local.py
- src/dvc_objects/fs/path.py
- tests/fs/test_localfs.py
Fixes https://github.com/iterative/dvc-objects/issues/177
`LocalFileSystem.path.normpath` was overriden to avoid using `urlsplit/urlunsplit`. This enables us to perform  `dvc add` for filenames with special characters not valid in URLs.
Related RPs: https://github.com/iterative/dvc/pull/8778
> localfs: remove urlsplit from path.normpath

- src/dvc_objects/fs/base.py
- src/dvc_objects/fs/utils.py
Adds naive `fs.utils.exists` implementation for querying batched file existence. Essentially it is a dumbed down and much less optimized alternative to what we do for querying ODB status.
For `version_aware` remotes, on `push` we need to check whether or not version IDs that we have in the .dvc file still exist in the remote (old object versions could have been removed from the bucket for a variety of reasons). If the version ID we have no longer exists, we should push the object again and update the .dvc file with the new version ID.
To check this existence we have two options:
1. Check existence using `fs.exists()` for each file we have to push
2. Use `fs.ls(<parent dir(s)>, versions=True)` calls and get a listing of all object versions in a given directory (and then compare that list …
> fs: add batch utils.exists implementaiton

- src/dvc_objects/fs/base.py
This speeds up `dvc version` from >1s to ~0.35s in my machine.
See https://docs.python.org/3/library/importlib.html#checking-if-a-module-can-be-imported.
> fs.get_missing_deps: use find_spec to check if packages are missing instead of importing them

- src/dvc_objects/fs/local.py
Related https://github.com/iterative/dvc/pull/9057
> localfs: get_file: handle dirs like fsspec's localfs

- setup.cfg
- src/dvc_objects/fs/base.py
```console
$ dvc data status
WARNING: 'fsspec>=2022.10.0' is required, but you have '2022.8.2' installed which is incompatible.
ERROR: unexpected error - 'ino'
```
> warn on incompatible fsspec installation

- src/dvc_objects/db.py
- src/dvc_objects/fs/generic.py
The transfer() api should not set sizes, as it's a responsibility of the caller. `transfer()` could be called with just one file to transfer, so a callback of size 1 does not make sense.
This broke `checkout` as it checks out one by one.
Related https://github.com/iterative/dvc/issues/6226.
Current dependencies on/for this PR:
- https://github.com/iterative/dvc-objects/pull/208 👈🏼 
- https://github.com/iterative/dvc-data/pull/355
- https://github.com/iterative/dvc/pull/9445
> transfer: callback: do not set sizes, do it in odb.add()

- src/dvc_objects/db.py
- tests/test_odb.py
Fixes bug where listing objects in DVC 2.x cache would include nonexistent paths due to 3.x hashes returned by `find()`
(previously it would only check the last 2 parts of a path, so `files/<md5>` still matched even when we were in the 2.x ODB)
> odb: verify that parts len is actually 2

- src/dvc_objects/fs/generic.py
Discovered this while playing with databricks. E.g. `dvc import-url` resulted in:
```
2023-07-27 01:02:33,446 DEBUG: v3.8.1 (pip), CPython 3.10.6 on Linux-5.15.0-1040-azure-x86_64-with-glibc2.35
2023-07-27 01:02:33,446 DEBUG: command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-5a432df4-b771-45c9-ad4e-de37cca00570/bin/dvc import-url https://archive.ics.uci.edu/static/public/186/wine+quality.zip -v
2023-07-27 01:02:36,628 DEBUG: Removing output 'wine+quality.zip' of stage: 'wine+quality.zip.dvc'.
2023-07-27 01:02:36,629 DEBUG: Removing '/Workspace/Repos/ruslan@iterative.ai/databricks-mlflow-end-to-end-example/wine+quality.zip'
Importing 'https://archive.ics.uci.edu/static/public/186/wine+quality.zip' -> 'wine+quality.zip'
2023-07-27 01:02:37,874 DEBUG: Computed stage: 'wine+quality.zip.dvc' …
```
> fs: transfer: don't raise if link failed with ENOSYS

- src/dvc_objects/fs/generic.py
Running into this on windows when working on a mapped network share https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d
The error I'm getting is:
```
OSError: [WinError 1] Incorrect function
```
which is mapped https://github.com/python/cpython/blob/5113ed7a2b92e8beabebe5fe2f6e856c52fbe1a0/PC/errmap.h#L132 to `EINVAL`.
Related to https://github.com/iterative/dvc/pull/9780
> fs: transfer: don't raise if link failed with EINVAL

- src/dvc_objects/fs/base.py
_prepare_credentials might check stuff and raise exceptions, which would prevent us from creating an fs instance lazilly.
Related https://github.com/iterative/studio/pull/6963
> fs: base: make fs_args lazy

- src/dvc_objects/fs/local.py
To fix https://github.com/iterative/dvc-objects/actions/runs/6162702142/job/16724739641#step:5:72Ç
Do we care about respecting the reference implementation? Should we add and honor the `on_error` arg instead?
> Fix pylint warning.

- src/dvc_objects/fs/generic.py
Otherwise we might run into `IndexError: list index out of range` if none link types are supported and we use on_error.
> generic: transfer: check if links are empty

- src/dvc_objects/fs/callbacks.py
- src/dvc_objects/fs/local.py
- tests/fs/test_callbacks.py
Fixes https://github.com/iterative/dvc/issues/9984
> callbacks: wrap non-dvc callbacks passed via fsspec

- src/dvc_objects/fs/utils.py
There is no reason to create a progress bar overhead for anything that takes < 2sec to copy on a modern machine.
Related https://github.com/iterative/dvc/issues/9914
> fs: copyfile: don't show progress for files < 1G

- src/dvc_objects/executors.py
- src/dvc_objects/fs/generic.py
More jobs is not better for localfs transfers. Even just using ThreadPoolExecutor with 1 job is already a significant penalty vs no pool at all.
There will be more details and high-level benchmark results in https://github.com/iterative/dvc/issues/9914
Related https://github.com/iterative/dvc-objects/pull/229
Related https://github.com/iterative/dvc/issues/9914
> fs: copy: limit to 1 job for localfs to localfs transfers

- noxfile.py
- pyproject.toml
- src/dvc_objects/fs/system.py
- tests/benchmarks/test_fs.py
10000 reflinks now take about 1sec instead of 2.7sec
> fs: system: optimize reflink

- src/dvc_objects/fs/system.py
We should set desired permissions explicitly in layers above this one.
For now just getting rid of this and proper permissions will be set up in the followups in `dvc_data.index.checkout`.
Overall it is pretty hard to imagine when cache would be read-only but reflinks would work.
Also important to note that `copy` flow may or may not clone permissions too, so we are not worsening things here much.
Related https://github.com/iterative/dvc-data/issues/274
Related https://github.com/iterative/dql/pull/1007#issuecomment-1841951977
> fs: reflink: don't try to reset permissions

- src/dvc_objects/fs/system.py
- tests/benchmarks/test_fs.py
- tests/test_reflink.py
```
test_link[_reflink]      1.3341 (1.0)      1.3341 (1.0)      1.3341 (1.0)      0.0000 (1.0)      1.3341 (1.0)      0.0000 (1.0)           0;0  0.7496 (1.0)           1           1
test_link[pyreflink]     1.4004 (1.05)     1.4004 (1.05)     1.4004 (1.05)     0.0000 (1.0)      1.4004 (1.05)     0.0000 (1.0)           0;0  0.7141 (0.95)          1           1
test_link[reflink]       1.6404 (1.23)     1.6404 (1.23)     1.6404 (1.23)     0.0000 (1.0)      1.6404 (1.23)     0.0000 (1.0)           0;0  0.6096 (0.81)          1           1
```
Only `chmod` is a problem.
Internal reflink is now 5% faster than pyreflink.
- Simplify code, remove unnecessary assertions, and makes import eager.
> microopt: reorder to remove assertions, lazy imports

- src/dvc_objects/fs/system.py
- tests/benchmarks/test_fs.py
- tests/conftest.py
- tests/test_reflink.py
This makes it possible to test Linux where tmpdir is using tmpfs rather than the filesystem that supports reflink.
Also we run test for 1000 links, but run 10 rounds (with 3 warmup rounds) for better results, as a single test may be noisy.
> bench: use .pytest_cache as tmpdir for running benchmarks

- src/dvc_objects/fs/utils.py
Related https://github.com/iterative/dvc-objects/pull/238
> fs: utils: copyfile: reset permissions on macos reflinks

- src/dvc_objects/fs/utils.py
Since dvc-data uses callback now on copyfile, we can cleanup unnecessary kwargs from here.
Note that this is a breaking change, as we cap only the major version in dvc-data. So this will require us to release 2.0 version.
> [breaking] utils: cleanup copyfile

- pyproject.toml
- src/dvc_objects/fs/base.py
dvc-objects cannot enforce a particular version of fsspec. It's upto dvc and dvc plugins to ensure this.
> filesystem: remove fsspec version check

- src/dvc_objects/db.py
This will format `repr` nicely if you use `rich` for printing (as I do in `pdb` and `ipython`).
This may be not useful for `repr(db)`, but if you, for example have a very verbose output, this becomes very useful.
Eg:
```python
StorageMapping(
{
(): StorageInfo(
data=None,
cache=ObjectStorage(
key=(),
odb=HashFileDB(
fs=<dvc_objects.fs.local.LocalFileSystem object at 0x1109e68d0>,
path='/private/var/folders/xh/trg29z296h70n109kwfk6g800000gn/T/pytest-of-saugat/pytest-278/pytest-servers13',
read_only=False
),
index=None,
read_only=False
),
remote=None
)
}
)
```
```python
StorageMapping({(): StorageInfo(data=None, cache=ObjectStorage(key=(), odb=HashFileDB(fs=<dvc_objects.fs.local.LocalFileSystem object at 0x1109e68d0>, path='/private/var/folders/xh/trg29z296h70n109kwfk6g800000gn/T/pytest-of-s …
```
> objectdb: add __rich_repr__

- pyproject.toml
- src/dvc_objects/fs/utils.py
- tests/fs/test_utils.py
Python>=3.6 has [`secrets.token_urlsafe`](https://docs.python.org/3/library/secrets.html#secrets.token_urlsafe) that can create cryptographically safe strings/numbers. So we don't need to use shortuuid. The generated text string is of the same size as `shortuuid.uuid()`, but can contain underscore and hyphen characters (not just alpha-numeric values), which might make it less human-readable. But I am not sure if it's worth it to use a third-party library (which can be gradually removed).
`token_urlsafe` is also 4x faster than `shortuuid.uuid()`.
> use token_urlsafe instead of shortuuid to generate temp file

- pyproject.toml
- src/dvc_objects/compat.py
- src/dvc_objects/fs/base.py
- src/dvc_objects/fs/local.py
cached_property on Python>=3.12 does not have a lock, so we can use it instead of funcy. This means that now we don't need to depend on funcy at all for Python>=3.12, and is optional.
> use functools.cached_property on Python>=3.12

- src/dvc_objects/fs/callbacks.py
`self.tqdm` should be set if progress_bar is passed.
> TqdmCallback: fix typo/off-by-one error
