src/dvc_objects/hashfile/db.py, src/dvc_objects/hashfile/obj.py
Turned out to be pretty convenient to have it (at least for now).
=> hashfile: add HashFile obj

src/dvc_objects/fs/implementations/_memory.py
We used to call `info()` for each object, now this will reuse the
object found during traversal.
Now only if we could optimize `info()` somehow. `open` now uses `info` instead of `isdir()`.
If we could optimize `info()`, it'd improve performance for `put`/`get`/`cp_file` etc.
=> memfs2: optimize ls/walk/find

.github/workflows/tests.yml
related: https://github.com/iterative/dvc-data/pull/98
=> ci: allow failures on 3.11

src/dvc_objects/fs/generic.py
fixes iterative/dvc#7865
thanks @alexmojaki
=> fs: hide tracebacks on _try_links failure

setup.cfg, src/dvc_objects/fs/implementations/gdrive.py
Simplifies logic using newly added pydrive2 helpers.
=> fs: gdrive: upgrade pydrive2

src/dvc_objects/fs/implementations/gdrive.py
Fixes https://github.com/iterative/dvc/issues/7984
=> fs: gdrive: don't save creds if tmp_dir is not available

setup.cfg, src/dvc_objects/fs/implementations/gdrive.py
Part of https://github.com/iterative/dvc/issues/7832
=> fs: gdrive: add gdrive_acknowledge_abuse

setup.cfg, src/dvc_objects/fs/implementations/http/__init__.py, src/dvc_objects/fs/implementations/http/retry.py
see https://github.com/iterative/dvc/issues/8100
=> fs: http: disable PUT/POST retries

src/dvc_objects/fs/__init__.py
Leftover from https://github.com/iterative/dvc-objects/pull/123
=> fs: fix registry

.github/workflows/tests.yml, noxfile.py, setup.cfg
Now that we don't need to install too many dependencies, we can get rid of caching.
Also made some simplifications to workflow.
=> simplify github actions workflow

src/dvc_objects/db.py
=> db: _init: don't forget leading zeros

src/dvc_objects/fs/base.py
=> fs: Fix mypy annotation for FileSystem.fs_args

src/dvc_objects/fs/local.py, tests/fs/test_localfs.py
Needed for iterative/dvc#8299.
=> Implement localfs.walk(..., detail=True)

src/dvc_objects/fs/local.py
Discovered in https://github.com/iterative/dvc/pull/8398#issuecomment-1271602452
=> localfs: walk: support modifying dirs inplace with detail=True

setup.cfg
Kudos @skshetry https://github.com/iterative/dvc/issues/8439
=> deps: bump fsspec to >=2022.5.0

src/dvc_objects/fs/generic.py
Currently DVC just reuses dvc-data `hashfile.transfer._log_exceptions` for some generic fs copy operations even though the function call args don't match any more (and the used `_log_exceptions` is supposed to be internal to dvc-data)
=> fs: add generic implementation of log_exceptions for transfer/copy

src/dvc_objects/db.py
As pointed out by @skshetry before in https://github.com/iterative/dvc-objects/pull/147#issuecomment-1249362678 we can at least try to `ls` to avoid redundant api calls.
Relevant for slow NFS setups as pointed out by @dberenbaum during his experiments on his home NAS.
=> db: _init: only try creating missing subdirs

src/dvc_objects/db.py
http doesn't have it implemented.
=> db: _init: don't forget to ignore NotImplementedError on ls

.pre-commit-config.yaml, pyproject.toml
See https://github.com/PyCQA/bandit.
=> add bandit, a security linter

src/dvc_objects/db.py
Cuts down unnecessary makedirs calls during initial db dir creation. Tested out with our user that reported that `dvc repro` on NFS went down from 3+ minutes to 1+ minute in his setup.
Effectively a followup to @skshetry 's comments on https://github.com/iterative/dvc-objects/pull/147 and other related PRs.
=> db: lazily create subdirs

src/dvc_objects/fs/base.py, src/dvc_objects/fs/path.py
Was starting to see some fs/path related type issues in mypy==0.990+ in DVC
=> fs: add type hints for fs.path

src/dvc_objects/db.py
see: https://github.com/iterative/dvc-data/pull/246#issuecomment-1370557960
=> odb: implement add(check_exists=...) flag

src/dvc_objects/fs/local.py
No longer needed after https://github.com/iterative/dvc-data/pull/262
=> fs: local: don't remove custom fs.checksum()

src/dvc_objects/db.py, src/dvc_objects/executors.py, src/dvc_objects/fs/base.py, src/dvc_objects/fs/callbacks.py, src/dvc_objects/fs/generic.py, tests/test_odb.py
- Adds `executors.batch_coros` for batching asyncio calls roughly equivalent to our `threadpool.imap_unordered`
- Moves all batching out of ODB and into fs-level calls
- asyncio batching used when available, threadpoolexecutor used otherwise
- Adds support for batched calls in `fs.generic.transfer`, `fs.generic.copy`
- Adds support for batched `odb.add()`
- Caller is still responsible for grouping oids by source filesystem (i.e. we handle this downstream in dvc-data transfer)
=> move threadpool usage out of odb and into fs

src/dvc_objects/fs/base.py, src/dvc_objects/fs/local.py, tests/fs/test_localfs.py
To comply with fsspec.
https://github.com/fsspec/filesystem_spec/blob/master/fsspec/implementations/local.py#L161 
Also closes https://github.com/iterative/dvc/issues/8757
=> fs: local: Accept list of paths in `rm`.

src/dvc_objects/db.py, src/dvc_objects/fs/base.py, tests/test_odb.py
=> db: use `find(prefix=True)` when listing oids by prefix

src/dvc_objects/fs/generic.py
=> fs: transfer: don't return on first exception

src/dvc_objects/fs/generic.py
Regression from https://github.com/iterative/dvc-objects/pull/199 🤦
Fixes https://github.com/iterative/dvc/issues/9098
Caught by @skshetry 🙏
=> generic: return when done copying

src/dvc_objects/db.py
Fixes https://github.com/iterative/dvc/issues/9735
=> odb: compare abspath to abspath in path_to_oid

src/dvc_objects/fs/generic.py
For filesystems that support `max_concurrency` within single file transfers (currently only adlfs), generic transfer methods now behave the same as fsspec batched put/get. When transferring a single file we set `max_concurrency=jobs`. When transferring more than one file we set `batch_size=jobs` and `max_concurrency=1`.
This implementation is naive and could be optimized further in the future (by actually balancing concurrent files and concurrent chunks within files), but for now this handles the worst-case scenario for these filesystems (single file upload/download)
Closes https://github.com/iterative/dvc-azure/issues/54
=> generic.transfer: support single file max_concurrency

src/dvc_objects/fs/local.py
Reverts iterative/dvc-objects#224
=> Revert "Fix pylint warning."

src/dvc_objects/fs/utils.py
This again wastes a lot of time, as `set_size` might trigger a pbar refresh.
Related https://github.com/iterative/dvc-objects/pull/229 Related https://github.com/iterative/dvc/issues/9914
=> fs: copyfile: don't touch callback at all for files <1G

src/dvc_objects/fs/system.py
Per https://github.com/iterative/dvc-objects/pull/234/files#r1416499169
=> fs: system: cleanup reflink

src/dvc_objects/fs/system.py
improves performance for Linux by as much as 50%.
Here's the result for reflinking 100,000 files
```console
--------------------------------------------------------------------------------- benchmark: 3 tests --------------------------------------------------------------------------------
Name (time in s)              Min               Max              Mean            StdDev            Median               IQR            Outliers     OPS            Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_link[reflink]         2.0291 (1.0)      2.1089 (1.0)      2.0594 (1.0)      0.0215 (1.00)     2.0548 (1.0)      0.0214 (1.0)           2;1 …
```
=> reflink: use os.open instead of builtin.open

src/dvc_objects/fs/generic.py
=> fs: generic: link: reset permissions on macos reflinks

src/dvc_objects/fs/base.py, src/dvc_objects/fs/callbacks.py, tests/fs/test_callbacks.py
Align with upstream fsspec implementation.
=> callback: improve TqdmCallback implementation

src/dvc_objects/fs/system.py
Fixes https://github.com/iterative/dvc/issues/10875.
=> support platforms with no os.link
